// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface authenticatorInfo {
    "index": number;
    "path": string;
    "product": string;
    "manufacturer": string;
    "productId": number;
    "vendorId": number;
    "windowsHello": boolean;
}

export interface dekRotationProgress {
    "phase": string;
    "completed": number;
    "total": number;
    "percent": number;
    "message": string;
}

export interface fidoEvent {
    "operationId": string;
    "phase": string;
    "message": string;
}

export interface vaultEntry {
    "alias": string;
    "value": vaultValueDocument;
    "revision": number;
    "createdAt": string;
    "updatedAt": string;
}

export interface vaultEntrySummary {
    "alias": string;
    "revision": number;
    "updatedAt": string;
}

export interface vaultReference {
    "name": string;
    "path": string;
    "lastOpenedAt": string;
    "available": boolean;
    "preferredDevicePath": string;
    "preferredDeviceProduct": string;
    "preferredDeviceManufacturer": string;
    "preferredDeviceVendorId": number;
    "preferredDeviceProductId": number;
}

export interface vaultStatus {
    "initialized": boolean;
    "unlocked": boolean;
    "selected": boolean;
    "vaultName": string;
    "vaultPath": string;
}

export interface vaultValueDocument {
    "version": number;
    "fields": vaultValueField[] | null;
}

export interface vaultValueField {
    "name": string;
    "value": string;
}
