// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddVault(path: string): $CancellablePromise<$models.vaultReference> {
    return $Call.ByID(1034230172, path);
}

export function Authenticators(): $CancellablePromise<$models.authenticatorInfo[] | null> {
    return $Call.ByID(772187589);
}

export function CloseVault(): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(3979838393);
}

export function Create(alias: string, value: $models.vaultValueDocument): $CancellablePromise<$models.vaultEntry> {
    return $Call.ByID(3576119441, alias, value);
}

export function Delete(alias: string, expectedRevision: number): $CancellablePromise<void> {
    return $Call.ByID(1946683094, alias, expectedRevision);
}

export function Get(alias: string): $CancellablePromise<$models.vaultEntry> {
    return $Call.ByID(2921188083, alias);
}

export function Initialize(devicePath: string, pin: string): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(1809546663, devicePath, pin);
}

export function List(): $CancellablePromise<$models.vaultEntrySummary[] | null> {
    return $Call.ByID(2700198509);
}

export function Lock(): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(337357262);
}

export function SelectVault(path: string): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(2605194843, path);
}

export function Status(): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(3998809027);
}

export function Unlock(devicePath: string, pin: string): $CancellablePromise<$models.vaultStatus> {
    return $Call.ByID(463265505, devicePath, pin);
}

export function Update(alias: string, value: $models.vaultValueDocument, expectedRevision: number): $CancellablePromise<$models.vaultEntry> {
    return $Call.ByID(1344403456, alias, value, expectedRevision);
}

export function Vaults(): $CancellablePromise<$models.vaultReference[] | null> {
    return $Call.ByID(2929502544);
}
